[custom.all.async-dom]
type   = "local"
path   = "."
ipkg   = "async-dom.ipkg"

[custom.all.async-dom-extra]
type   = "local"
path   = "extra"
ipkg   = "async-dom-extra.ipkg"

[custom.all.async-dom-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all]
css.commit             = "latest:main"
ref1.commit            = "latest:main"
array.commit           = "latest:main"
async.commit           = "latest:main"
streams.commit         = "latest:main"
http-types.commit      = "latest:main"
http-client-api.commit = "latest:main"
